config/routes.rb
Rails.application.routes.draw do
  resources :product_properties
  resources :categories
  resources :products
  # Get /home
  get "home", to: "home#index"
  get 'product', to:'products#index'
  root 'home#index'
  get 'category', to: 'categories#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
    validates :title, :image_url, :presence => true# khong duoc bo trong
    validates :price, :numericality => {:greater_than_or_equal_to => 1000}#gia tri nhap vao lon hon 1000
    validates :title, :uniqueness => true #duy nhat, khong the giong nhau
    validates :image_url, :format => {
        :with => %r{\.(gif|jpg|png)\Z}i,
        :message => 'Chi nhan file GIF, JPG, PNG'}
    belongs_to :category
    has_many :product_properties
    accepts_nested_attributes_for :product_properties
end

app/models/product_property.rb
class ProductProperty < ApplicationRecord
  belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:category)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    flash.now[:notice] = "Logged in successfully"
    flash.now[:alert] = "Invalid email or password"
  end
end

app/controllers/product_properties_controller.rb
class ProductPropertiesController < ApplicationController
  before_action :set_product_property, only: %i[ show edit update destroy ]

  # GET /product_properties or /product_properties.json
  def index
    @product_properties = ProductProperty.all
  end

  # GET /product_properties/1 or /product_properties/1.json
  def show
  end

  # GET /product_properties/new
  def new
    @product_property = ProductProperty.new
  end

  # GET /product_properties/1/edit
  def edit
  end

  # POST /product_properties or /product_properties.json
  def create
    @product_property = ProductProperty.new(product_property_params)

    respond_to do |format|
      if @product_property.save
        format.html { redirect_to @product_property, notice: "Product property was successfully created." }
        format.json { render :show, status: :created, location: @product_property }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product_property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_properties/1 or /product_properties/1.json
  def update
    respond_to do |format|
      if @product_property.update(product_property_params)
        format.html { redirect_to @product_property, notice: "Product property was successfully updated." }
        format.json { render :show, status: :ok, location: @product_property }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product_property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_properties/1 or /product_properties/1.json
  def destroy
    @product_property.destroy
    respond_to do |format|
      format.html { redirect_to product_properties_url, notice: "Product property was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_property
      @product_property = ProductProperty.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_property_params
      params.require(:product_property).permit(:version, :imageproduct_url, :in_stock, :product_id)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index 
    @products= Product.page(params[:page]).per(2)
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @product.product_properties.build
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :sku, :price, :quantity, :image_url, :term, :category_id,product_properties_attributes: [:id, :version, :imageproduct_url, :in_stock])      
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def link_to_add_fields(name, f, association)
        #create a new object from the association (:product_properties)
        new_object = f.object.send(association).klass.new

        # just create or take the id from the new object
        id =new_object.object_id

        # create the new form
        fields =f.fields_for(association,new_object,child_index: id) do |builder|
            render(association.to_s.singularize + "_fields",f: builder)
    end
     
    # pass down the link to the fields form
    link_to(name, "#", class: 'add_fields', data: {id: id, fields: fields.gsub("\n","")})
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/product_properties_helper.rb
module ProductPropertiesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
     
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.category %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @category.category %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/home/index.html.erb
<div class="d-flex align-items-center justify-content-center">
<h1>WELCOME TO BOOKSTORE</h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductManagementApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   
  </head>

  <body>

  <%= render partial: "shared/navbar"%>
  
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/product_properties/_form.html.erb
<%= form_with(model: product_property) do |form| %>
  <% if product_property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product_property.errors.count, "error") %> prohibited this product_property from being saved:</h2>

      <ul>
        <% product_property.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :version %>
    <%= form.text_field :version %>
  </div>

  <div class="field">
    <%= form.label :imageproduct_url %>
    <%= form.text_field :imageproduct_url %>
  </div>

  <div class="field">
    <%= form.label :in_stock %>
    <%= form.text_field :in_stock %>
  </div>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/product_properties/edit.html.erb
<h1>Editing Product Property</h1>

<%= render 'form', product_property: @product_property %>

<%= link_to 'Show', @product_property %> |
<%= link_to 'Back', product_properties_path %>

app/views/product_properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Product Properties</h1>

<table>
  <thead>
    <tr>
      <th>Version</th>
      <th>Imageproduct url</th>
      <th>In stock</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product_properties.each do |product_property| %>
      <tr>
        <td><%= product_property.version %></td>
        <td><%= product_property.imageproduct_url %></td>
        <td><%= product_property.in_stock %></td>
        <td><%= product_property.product_id %></td>
        <td><%= link_to 'Show', product_property %></td>
        <td><%= link_to 'Edit', edit_product_property_path(product_property) %></td>
        <td><%= link_to 'Destroy', product_property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product Property', new_product_property_path %>

app/views/product_properties/new.html.erb
<h1>New Product Property</h1>

<%= render 'form', product_property: @product_property %>

<%= link_to 'Back', product_properties_path %>

app/views/product_properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Version:</strong>
  <%= @product_property.version %>
</p>

<p>
  <strong>Imageproduct url:</strong>
  <%= @product_property.imageproduct_url %>
</p>

<p>
  <strong>In stock:</strong>
  <%= @product_property.in_stock %>
</p>

<p>
  <strong>Product:</strong>
  <%= @product_property.product_id %>
</p>

<%= link_to 'Edit', edit_product_property_path(@product_property) %> |
<%= link_to 'Back', product_properties_path %>

app/views/products/_form.html.erb
<%= form_for @product do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :sku %>
    <%= form.text_field :sku %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div>
    <%= form.select :category_id, Category.all.map {|c| [c.category,c.id]} %>
  </div>

  <div class = "field">
    <%= form.fields_for :product_properties do |f| %>
    
    <% end %>

  <%= link_to_add_fields "Add Property", form, :product_properties %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<script>

$('form').on('click','.remove_fields', function(event) {
  $(this).prev('input[type=hidden]').val('1');
  $(this).closest('fieldset').hide();
  return event.preventDefault();
});

$('form').on('click','.add_fields', function(event) {
  console.log('clicked')
  var regexp, time;
  time = new Date().getTime();
  regexp = new RegExp($(this).data('id'), 'g');
  $(this).before($(this).data('fields').replace(regexp, time));
  return event.preventDefault();
});

</script>

app/views/products/_product_property_fields.html.erb
    <%= f.label :version %>
    <%= f.text_field :version %>
    <%= f.label :imageproduct_url%>
    <%= f.text_field :imageproduct_url %>
    <%= f.label :in_stock %>
    <%= f.text_field :in_stock %>
    <%= f.hidden_field :_destroy %>
    <%= link_to "Remove", "#", class: 'remove-fields' %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1 class="text-left" style="color: black;">All Products</h1>
<div class="col-md-10 col-lg-offset-1">
   <div id="product_list">
    <table>
    <% @products.each do |product| %>
        <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
  
            <td>
                <%= image_tag(product.image_url, :class => 'list_image') %>
            </td> 
  
            <td class="list_title">
                <dl>
                    <dt><%= product.title %></dt>
                    <dt>
                        <p>
                        Price: 
                        <%= product.price %>
                        </p>
                    </dt>
                </dl>
            </td>
           
            <td class="list_actions">
                <%= link_to 'Show', product %><br/>
                <%= link_to 'Edit', edit_product_path(product) %><br/>
                <%= link_to 'Destroy', product,data: { confirm: 'Are you sure?' },:method => :delete %>
            </td>
        </tr>
    <% end %>
    </table>
</div>
 
<br />
    <%= will_paginate @products %>
    <%= link_to 'New product', new_product_path %>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<h1> Category: <%= @product.category.category %></h1>
<big> 
<b>
  <%= @product.title%>
</b>
</big>

<p>
  <strong>Sku:</strong>
  <%= @product.sku %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<p>
  <strong> Available Properties: <%= @product.product_properties.count %> </strong>

 <% @product.product_properties.each do |property| %>
</p>
  
    <%= property.version %>
    <%= property.imageproduct_url %>
    <%= property.in_stock %>
<p>
<% end %>

</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
<div class="alert alert-info mt-4" role= "alert">
    <%= flash[:notice] %>
</div>
<% end %>

<% if flash[:alert] %>
<div class="alert alert-warning mt-4">
<%= flash[:alert] %>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">BOOK STORE</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to "Home", home_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
           <%= link_to "Product", products_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
           <%= link_to "Category", categories_path, class:"nav-link" %>
        </li>
      </ul>
      <form class="d-flex">
      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
    </div>
  </div>
</nav>